name: Scheduled ADP Scraper

on:
  schedule:
    # Run twice per day at 8 AM and 8 PM Phoenix time.
    # Phoenix is on America/Phoenix (UTC−7) all year, so convert to UTC:
    # 8 AM MST → 15:00 UTC, 8 PM MST → 03:00 UTC the next day.
    - cron: '0 15 * * *'
    - cron: '0 3 * * *'
  workflow_dispatch: {}

# Needed for pushing commits and opening PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    concurrency:
      group: adp-scraper
      cancel-in-progress: true

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the fantasy basketball ADP scraper
        env:
          TZ: America/Phoenix
        run: |
          python fantasy_adp_scraper.py --output adp_data.csv

      # Commit changes to a dedicated bot branch (avoids non-fast-forward on main)
      - name: Commit changes to bot branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update ADP data"
          file_pattern: adp_data.csv
          branch: bot/adp-update
          create_branch: true

      # Open or update a PR from bot/adp-update -> main
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/adp-update        # reuse the same branch so the PR gets updated
          base: main
          title: "Update ADP data"
          body: |
            Automated ADP refresh from the scheduled workflow.
            - Timezone: America/Phoenix
            - Changes: updates to `adp_data.csv`
          labels: |
            automated
            data-update
