name: Scheduled Auction Value Scraper

on:
  # schedule:
  #   # Run every 2 hours
  #   - cron: '0 */2 * * *'
  workflow_dispatch: {}  # Keep manual trigger enabled

# Needed for pushing commits and opening PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    concurrency:
      group: auction-scraper
      cancel-in-progress: true

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the fantasy basketball auction value scraper
        env:
          TZ: America/Phoenix
        run: |
          python fantasy_auction_scraper.py --output auction_data.csv

      # Commit changes to a dedicated bot branch (avoids non-fast-forward on main)
      - name: Commit changes to bot branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update auction value data"
          file_pattern: auction_data.csv
          branch: bot/auction-update
          create_branch: true

      # Open or update a PR from bot/auction-update -> main
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/auction-update        # reuse the same branch so the PR gets updated
          base: main
          title: "Update auction value data"
          body: |
            Automated auction value refresh from the scheduled workflow.
            - Timezone: America/Phoenix
            - Changes: updates to `auction_data.csv`
            - Sources: Yahoo, ESPN (from Hashtag Basketball)
          labels: |
            automated
            data-update
